val_ pk
Use val_ to transform `AddresT Identity` to `AddresT (QExpr ...)`. I'm
still missing something, as the comilation fails due to ambiguous type
variables in the `pk`, `default_`, and `Maybe Text` fields.

  ghc --make quickie.hs -no-keep-hi-files -no-keep-o-files

  quickie.hs:128:29: error:
      • Couldn't match expected type ‘beam-core-0.8.0.0:Database.Beam.Query.Combinators.HaskellLiteralForQExpr
                                        (Columnar f0 (Maybe Text))’
                    with actual type ‘Maybe a0’
        The type variables ‘f0’, ‘a0’ are ambiguous
      • In the first argument of ‘val_’, namely ‘Nothing’
        In the third argument of ‘Address’, namely ‘(val_ Nothing)’
        In the expression:
          Address
            default_
            (val_ "123 Little Street")
            (val_ Nothing)
            (val_ "Boston")
            (val_ "MA")
            (val_ "12345")
            (val_ (pk james))
      • Relevant bindings include
          addresses :: [AddressT f0] (bound at quickie.hs:125:7)
      |
  128 |                       (val_ Nothing)
      |                             ^^^^^^^

  quickie.hs:132:30: error:
      • Couldn't match expected type ‘beam-core-0.8.0.0:Database.Beam.Query.Combinators.HaskellLiteralForQExpr
                                        (PrimaryKey UserT f0)’
                    with actual type ‘PrimaryKey UserT Identity’
        The type variable ‘f0’ is ambiguous
      • In the first argument of ‘val_’, namely ‘(pk james)’
        In the 7th argument of ‘Address’, namely ‘(val_ (pk james))’
        In the expression:
          Address
            default_
            (val_ "123 Little Street")
            (val_ Nothing)
            (val_ "Boston")
            (val_ "MA")
            (val_ "12345")
            (val_ (pk james))
      • Relevant bindings include
          addresses :: [AddressT f0] (bound at quickie.hs:125:7)
      |
  132 |                       (val_ (pk james))
      |                              ^^^^^^^^

  quickie.hs:142:23: error:
      • Couldn't match type ‘Columnar f0 Int’
                       with ‘Database.Beam.Query.Internal.QGenExpr ctxt0 be0 s0 a1’
        Expected type: C f0 Int
          Actual type: Database.Beam.Query.Internal.QGenExpr
                         ctxt0 be0 s0 a1
        The type variables ‘f0’, ‘ctxt0’, ‘be0’, ‘s0’, ‘a1’ are ambiguous
      • In the first argument of ‘Address’, namely ‘default_’
        In the expression:
          Address
            default_
            (val_ "9999 Residence Ave")
            (val_ Nothing)
            (val_ "Sugarland")
            (val_ "TX")
            (val_ "8989")
            (val_ (pk betty))
        In the expression:
          [Address
             default_
             (val_ "123 Little Street")
             (val_ Nothing)
             (val_ "Boston")
             (val_ "MA")
             (val_ "12345")
             (val_ (pk james)),
           Address
             default_
             (val_ "222 Main Street")
             (val_ (Just "Ste 1"))
             (val_ "Houston")
             (val_ "TX")
             (val_ "8888")
             (val_ (pk betty)),
           Address
             default_
             (val_ "9999 Residence Ave")
             (val_ Nothing)
             (val_ "Sugarland")
             (val_ "TX")
             (val_ "8989")
             (val_ (pk betty))]
      • Relevant bindings include
          addresses :: [AddressT f0] (bound at quickie.hs:125:7)
      |
  142 |                       default_
      |                       ^^^^^^^^

  quickie.hs:154:27: error:
      • Couldn't match type ‘f0’
                       with ‘Database.Beam.Query.Internal.QExpr
                               Database.Beam.Sqlite.Connection.Sqlite s'’
          because type variable ‘s'’ would escape its scope
        This (rigid, skolem) type variable is bound by
          a type expected by the context:
            forall s'.
            [AddressT
               (Database.Beam.Query.Internal.QExpr
                  Database.Beam.Sqlite.Connection.Sqlite s')]
          at quickie.hs:154:9-35
        Expected type: [AddressT
                          (Database.Beam.Query.Internal.QExpr
                             Database.Beam.Sqlite.Connection.Sqlite s')]
          Actual type: [AddressT f0]
      • In the first argument of ‘insertExpressions’, namely ‘addresses’
        In the second argument of ‘($)’, namely
          ‘insertExpressions addresses’
        In the second argument of ‘($)’, namely
          ‘insert (_shoppingCartUserAddresses shoppingCartDb)
             $ insertExpressions addresses’
      • Relevant bindings include
          addresses :: [AddressT f0] (bound at quickie.hs:125:7)
      |
  154 |         insertExpressions addresses
      |                           ^^^^^^^^^