insertExpressions (type error)
This fails to compile due to type errors. My best guess is that the root
of the problem is hinted at by the last error, which complains about a
mismatch in the type of `f` in `AddressT f`. I'm passing a list of
`AddressT Identity` values, but it seems `insertExpressions` expects a
list of `AddressT QExpr Sqlite s` expressions.

The full errors are show below:

  ghc --make quickie.hs -no-keep-hi-files -no-keep-o-files
  [1 of 1] Compiling Main             ( quickie.hs, quickie.o )

  quickie.hs:126:23: error:
      • Couldn't match type ‘Database.Beam.Query.Internal.QGenExpr
                               ctxt0 be2 s0 a0’
                       with ‘Int’
        Expected type: C Identity Int
          Actual type: Database.Beam.Query.Internal.QGenExpr
                         ctxt0 be2 s0 a0
      • In the first argument of ‘Address’, namely ‘default_’
        In the expression:
          Address
            default_
            (val_ "123 Little Street")
            (val_ Nothing)
            (val_ "Boston")
            (val_ "MA")
            (val_ "12345")
            (pk james)
        In the expression:
          [Address
             default_
             (val_ "123 Little Street")
             (val_ Nothing)
             (val_ "Boston")
             (val_ "MA")
             (val_ "12345")
             (pk james),
           Address
             default_
             (val_ "222 Main Street")
             (val_ (Just "Ste 1"))
             (val_ "Houston")
             (val_ "TX")
             (val_ "8888")
             (pk betty),
           Address
             default_
             (val_ "9999 Residence Ave")
             (val_ Nothing)
             (val_ "Sugarland")
             (val_ "TX")
             (val_ "8989")
             (pk betty)]
      |
  126 |                       default_
      |                       ^^^^^^^^

  quickie.hs:134:23: error:
      • Couldn't match type ‘Database.Beam.Query.Internal.QGenExpr
                               ctxt1 be1 s1 a1’
                       with ‘Int’
        Expected type: C Identity Int
          Actual type: Database.Beam.Query.Internal.QGenExpr
                         ctxt1 be1 s1 a1
      • In the first argument of ‘Address’, namely ‘default_’
        In the expression:
          Address
            default_
            (val_ "222 Main Street")
            (val_ (Just "Ste 1"))
            (val_ "Houston")
            (val_ "TX")
            (val_ "8888")
            (pk betty)
        In the expression:
          [Address
             default_
             (val_ "123 Little Street")
             (val_ Nothing)
             (val_ "Boston")
             (val_ "MA")
             (val_ "12345")
             (pk james),
           Address
             default_
             (val_ "222 Main Street")
             (val_ (Just "Ste 1"))
             (val_ "Houston")
             (val_ "TX")
             (val_ "8888")
             (pk betty),
           Address
             default_
             (val_ "9999 Residence Ave")
             (val_ Nothing)
             (val_ "Sugarland")
             (val_ "TX")
             (val_ "8989")
             (pk betty)]
      |
  134 |                       default_
      |                       ^^^^^^^^

  quickie.hs:142:23: error:
      • Couldn't match type ‘Database.Beam.Query.Internal.QGenExpr
                               ctxt2 be0 s2 a2’
                       with ‘Int’
        Expected type: C Identity Int
          Actual type: Database.Beam.Query.Internal.QGenExpr
                         ctxt2 be0 s2 a2
      • In the first argument of ‘Address’, namely ‘default_’
        In the expression:
          Address
            default_
            (val_ "9999 Residence Ave")
            (val_ Nothing)
            (val_ "Sugarland")
            (val_ "TX")
            (val_ "8989")
            (pk betty)
        In the expression:
          [Address
             default_
             (val_ "123 Little Street")
             (val_ Nothing)
             (val_ "Boston")
             (val_ "MA")
             (val_ "12345")
             (pk james),
           Address
             default_
             (val_ "222 Main Street")
             (val_ (Just "Ste 1"))
             (val_ "Houston")
             (val_ "TX")
             (val_ "8888")
             (pk betty),
           Address
             default_
             (val_ "9999 Residence Ave")
             (val_ Nothing)
             (val_ "Sugarland")
             (val_ "TX")
             (val_ "8989")
             (pk betty)]
      |
  142 |                       default_
      |                       ^^^^^^^^

  quickie.hs:154:27: error:
      • Couldn't match type ‘Identity’
                       with ‘Database.Beam.Query.Internal.QGenExpr
                               Database.Beam.Query.Internal.QValueContext
                               Database.Beam.Sqlite.Connection.Sqlite
                               s'’
        Expected type: [AddressT
                          (Database.Beam.Query.Internal.QExpr
                             Database.Beam.Sqlite.Connection.Sqlite s')]
          Actual type: [AddressT Identity]
      • In the first argument of ‘insertExpressions’, namely ‘addresses’
        In the second argument of ‘($)’, namely
          ‘insertExpressions addresses’
        In the second argument of ‘($)’, namely
          ‘insert (_shoppingCartUserAddresses shoppingCartDb)
             $ insertExpressions addresses’
      |
  154 |         insertExpressions addresses
      |                           ^^^^^^^^^